version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.0
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample
    branches:
      ignore:
        - gh-pages # list of branches to ignore
        - /release\/.*/ # or ignore regexes
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install dependences
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install MySQL CLI; Waiting and import dummy data; run an example query
          command: |
            sudo apt-get install mysql-client
            dockerize -wait tcp://localhost:3306 -timeout 1m
            mysql -h 127.0.0.1 -u root -proot sample < __test__/sample.sql
      - run:
          name: test
          environment:
            MYSQL_URL: "mysql://root:root@localhost:3306/sample"
          command: yarn test:cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
